name: Master
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'	
          architecture: 'x64' 
      - run: python main.py ${{ secrets.DISCORD_WEBHOOK }}
      
